# See https://github.com/netlify/netlify-cms/blob/master/example/config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# display_url: https://gatsbro.netlify.com # This url will display in the top-right of the CMS
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Page"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: true
    files:
      - file: "content/pages/home.md"
        label: "Home Page"
        name: "home-page"
        fields:
          - {name: template, label: Template, widget: hidden, default: 'HomePage'}
          - {name: slug, label: Slug, widget: hidden, default: ''}
          - {name: video, label: video, widget: string, required: true, default: ''}
          - {name: title, label: Title, widget: string, default: ''}
          - {name: featuredImage, label: Featured Image, widget: image}
          - name: featureButton
            label: Feature Button
            widget: object
            fields:
              - {name: label, label: label, widget: string, required: false, default: ''}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - {name: welcomeTitle, label: Welcome Title, widget: string, required: false, default: ''}
          - name: welcomeButton
            label: Welcome Button
            widget: object
            fields:
              - {name: label, label: label, widget: string, required: false, default: ''}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - {name: newField, label: New Field, widget: string, required: false, default: ''}
          - {name: servicesTitle, label: Services Title, widget: string, required: false, default: ''}
          - {name: bannerTitle, label: Banner Title, widget: string, required: false}
          - {name: bannerDescription, label: Banner Description, widget: text, required: false}
          - {name: bannerImage, label: bannerImage, widget: image, required: false}
          - name: bannerButton
            label: Banner Button
            widget: object
            fields:
              - {name: label, label: label, widget: string, required: false, default: ''}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - {name: teamTitle, label: Team Title, widget: string, required: false, default: ''}
          - {name: teamDescription, label: Team Description, widget: text, required: false, default: ''}
          - {name: teamImage, label: Team Image, widget: image, required: false}
          - name: teamButton
            label: Team Button
            widget: object
            fields:
              - {name: label, label: label, widget: string, required: false, default: ''}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - name: "benefits"
            label: "Benefits"
            widget: "list"
            fields:
              - {name: icon, label: Icon, widget: image}
              - {name: title, label: Title, widget: string, default: ''}
              - {name: description, label: Description, widget: markdown, default: ''}
          - {name: videoTitle, label: Video Title, widget: string, required: false, default: ''}
          - {name: videoContent, label: Video Content, widget: markdown, required: false default:''}
          - {name: videoURL, label: Video URL, widget: string, required: false, default: ''}
          - {name: priceTitle, label: Price Title, widget: string, required: false, default: ''}
          - {name: priceDescription, label: Price Description, widget: text, required: false, default: ''}
          - name: priceButton
            label: Price Button
            widget: object
            fields:
              - {name: label, label: label, widget: string, required: false, default: ''}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - {name: partnersTitle, label: Partners Title, widget: string, required: false, default: ''}
          - name: "partnerLogos"
            label: "Partner Logos"
            widget: "list"
            default: ['logo', 'link']
            fields:
              - {name: logo, label: Logo, widget: image, required: false}
              - {name: link, label: Link, widget: string, required: false, default: ''}
          - label: "Meta"
            required: false
            name: "meta"
            widget: "object"
            fields:
              - {name: title, label: Title,  widget: string, required: false}
              - {name: description, label: Description, widget: text, required: false, pattern: [".{,300}", "Must not exceed 300 characters"]}
              - {name: canonicalLink, label: Canonical Link, widget: string, required: false}
              - {name: noindex, label: Noindex, widget: boolean, required: false}
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/settings/global.yml"
        label: "Global Settings"
        name: "global-settings"
        fields:
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: phone, name: phone, widget: string, required: false}
          - {label: phone2, name: phone2, widget: string, required: false}
          - {label: email, name: email, widget: string, required: false}
          - {label: subscribeFormTitle, name: subscribeFormTitle, widget: string, required: false}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Image, name: image, widget: image, required: false}
              - {label: twitter, name: twitter, widget: string, required: false}
              - {label: facebook, name: facebook, widget: string, required: false}
              - {label: instagram, name: instagram, widget: string, required: false}
              - {label: youtube, name: youtube, widget: string, required: false}
          - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}
